Zoom sdk update
testpress/android pull request #178
Opened 2021-05-17 10:43 UTC by NavayuvanSB

### Changes done
- Update zoom sdk to latest version

### Reason for the changes
- Previously integrated zoom sdk version is depreciated

### Guidelines
- [x] Have you self reviewed this PR in context to the previous PR feedbacks?

2021-05-17 11:11 UTC, Karthik-0 requested changes

2021-05-17 11:11 UTC, Karthik-0 commented on app/build.gradle
> +
Please undo this change

2021-05-17 11:11 UTC, Karthik-0 commented on app/build.gradle
> +    // implementation 'in.testpress:course:1.0.0'
Please undo these changes

2021-05-17 11:11 UTC, Karthik-0 commented on build.gradle
> +
This file should not be added as this change is not necessary

2021-05-17 11:17 UTC, NavayuvanSB commented
Comments resolved @Karthik-0, please review it.

2021-05-20 07:27 UTC, closed without merging

2021-05-20 07:30 UTC, NavayuvanSB commented
Refer #180 for further progress.